### ISSUE TITLE
Configurable blur level?

### ISSUE THREAD

**Issue by alexellis** [esimov/pigo-openfaas-faceblur#1]
Hi,

Could we tweak the face-detection level and / or the blur level?

Some of the examples I ran show the face very clearly afterwards.

```
export IMG=https://pbs.twimg.com/media/D7Z0ew_UwAE922w.jpg

time curl -SLs https://teamserverless.o6s.io/pigo-faceblur \
   --data-binary $IMG > img1.jpg

export IMG=https://pbs.twimg.com/media/D7LecYgXsAI6boC.jpg


time curl -SLs https://teamserverless.o6s.io/pigo-faceblur \
   --data-binary $IMG > img2.jpg

export IMG=https://pbs.twimg.com/media/D7LC5hsXoAU_qF9.jpg 
time curl -SLs https://teamserverless.o6s.io/pigo-faceblur --data-binary $IMG > img3.jpg
```

Alex

**Comment by esimov** [comment]
The reason why the blur level is too small is strictly related to the correlation between the detected face sizes and the applied blur weight. This means the same amount of blur size is applied without considering the image size. The function can be adapted in such a way that we can calculate the blur size depending on the detected face region dimension and apply a weight ratio.
